config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :homes
  resources :contacts, only: [:new, :create]
  resources :users, only: [:index, :new, :create, :update, :show, :destroy]
  resources :messages, only: [:update, :show, :edit, :destroy]
  resources :tests , except: [:update]
  #PDF feature
  resources :invoices, only: [:index, :show]
  resources :invoices, only: [:index, :show] do
    resource :download, only: [:show]
  end

  # resources :carts do
  #   collection do
  #     delete :clean
  #   end
  # end
  # resources :items, controller: 'cart_items'
  resources :payment_records
  resources :payout_records
  resources :test_records
  resources :qars
  resources :prompts
  resources :responses

  delete 'logout'  => 'sessions#destroy'
  get '/resendtokenpage' => 'application#resendtokenpage'
  post '/resendtoken' => 'application#resendtoken'
  get '/resendtokensuccessful' => 'application#resendtokensuccessful'

  get '/activeuser' => 'application#activeuser'

  post '/forget_email' => 'application#forget_email'
  post '/forget_password' => 'application#forget_password'

  get '/resetpassword' => 'application#getresetpassword'
  post '/resetpassword' => 'application#postresetpassword'

  get '/resetpasswordsuccessful' => 'application#resetpasswordsuccessful'


  match '/login' => 'users#login', :via => [:post, :get]
  match '/logout' => 'users#logout', :via => [:post, :get]

  get '/thankyou' => 'homes#thankyou'

  get '/active_link_done' => 'homes#active_link_done'
  get '/active_link_fail' => 'homes#active_link_fail'

  # homes inner pages routes
  # get '/howitworks' => 'homes#howitworks'
  # get '/aboutthetests' => 'homes#aboutthetests'
  # get '/aboutparrot' => 'homes#aboutparrot'
  # get '/parrotforbusiness' => 'homes#parrotforbusiness'
  # get '/howtobecomeaparrotrater' => 'homes#howtobecomeaparrotrater'
  # get '/contactus' => 'homes#contactus'
  # get '/test' => 'homes#testtemplate'
  # get '/faq' => 'homes#faq'
  # get '/privatepolicy' => 'homes#privatepolicy'
  get '/test_introduction/:id(.:format)' => 'homes#test_introduction', :as => 'test_introduction'
  match '/search_tests' => 'homes#search_tests', :via => [:post, :get]
  get '/notfound' => 'application#not_found'



  # cart
  # post '/save_item' => 'tests#save_item'
  post '/add_to_cart' => 'tests#add_to_cart'
  get '/cart_number_reload' => 'homes#cart_number_reload'
  get '/cart' => 'carts#cart'
  post '/delete_item' => 'carts#delete_item'
  post '/clean_cart' => 'carts#clean_cart'
  post '/cart_login' => 'carts#cart_login'

  # payment
  get '/checkout' => 'paypals#new'
  post '/checkout_with_credit_card' => 'paypals#checkout_with_credit_card'
  post '/checkout_with_paypal' => 'paypals#checkout_with_paypal'
  get '/thankyoupurchase' => 'paypals#thankyoupurchase'
  post '/cancel_order' => 'paypals#cancel_order'
  get '/payout_new' => 'paypals#payout_new'
  match '/payout_create' => 'paypals#payout_create', :via => [:post, :get]
  get '/payment_pdf' => 'payment_records#download_payment_pdf'


  # admin home
  get '/dashboard' => 'users#dashboard'
  get '/cashflow' => 'users#cashflow'
  get '/invite' => 'users#invite'
  post '/invite_user' => 'users#invite_user'
  post '/invite_as_rater' => 'users#invite_as_rater'
  get '/cheating/:id(.:format)' => 'users#cheating', :as => 'cheating'
  post '/change_user_status' => 'users#change_user_status'

  # cms
  get '/cms' => 'users#cms'
  get '/cms/:id/edit(.:format)' => 'users#page_edit', :as => 'page_edit'
  post '/tinymce_assets' => 'users#upload_image'
  put '/cms/content_update/:id(.:format)' => 'users#content_update', :as => 'content_update'

  # user home
  get '/home' => 'users#home'
  get '/account' => 'users#edit', :as => 'edit_user'
  get '/payment' => 'payment_records#index'
  get '/test_brief/:id(.:format)' => 'tests#test_brief', :as => 'test_brief'
  post '/test_checkout' => 'tests#test_checkout'
  # get '/prompts' => 'users#prompts'
  # post '/change_password' => 'users#change_password'
  get '/certificate_pdf' => 'users#download_certificate_pdf'

  # rater home
  get '/rating_history' => 'users#rating_history'

  # test
  put '/tests/:id(.:format)' => 'tests#update', :as => 'test_update'
  get '/sendscores' => 'test_records#sendscores'
  get '/score_histiry' => 'test_records#score_histiry'
  post '/send_response' => 'tests#send_response'
  post '/close_test' => 'tests#close_test'
  get '/finished_test' => 'tests#finished_test'
  # get '/test_begin_camera' => 'test_records#test_begin_camera'
  post '/post_test_begin_photo' => 'test_records#post_test_begin_photo'
  # get '/test_end_camera' => 'test_records#test_end_camera'
  post '/post_test_end_photo' => 'test_records#post_test_end_photo'
  post '/window_lose_focus' => 'tests#window_lose_focus'
  post '/take_practice_test/:id(.:format)' => 'tests#take_practice_test', :as => 'take_practice_test'

  # response
  post '/change_response_type' => 'responses#change_response_type'
  post '/audio_record_create' => 'responses#audio_record_create'
  get '/rater_available' => 'responses#rater_available'
  get '/photo_verification/:id(.:format)' => 'test_records#photo_verification', :as => 'photo_verification'
  post '/post_photo_verification' => 'test_records#post_photo_verification'
  get '/rate_response/:id(.:format)' => 'responses#rate_response', :as => 'rate_response'
  match '/give_a_rate' => 'responses#give_a_rate', :via => [:post, :get]
  post '/test_answer' => 'responses#test_answer'
  # get '/recorder' => 'responses#recorder'
  post '/qar_submit' => 'qars#qar_submit'

  # Contact us
  get '/contact_us' => 'messages#index', :as => 'messages'
  get '/new_message' => 'messages#new', :as => 'new_message'
  post '/contact_us' => 'messages#create'
  post '/message_delete' => 'messages#delete'
  post '/message_reply' => 'messages#reply'
  get '/inbox_reload' => 'messages#inbox_reload'
  get '/sendbox_reload' => 'messages#sendbox_reload'


  get '/:slug' => 'homes#find_page'
  # get '*slug' => 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_ancestry
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authuser

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    @inbox_messages = Message.where(:to_user_id => @current_user.id.to_s).or(Message.where(:is_system_notification => 1)).order("created_at DESC")
    @sendbox_messages = Message.where(:user_id => @current_user.id.to_s).order("created_at DESC")
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = @message
    @parent = Message.find_by_id(@reply_message_id)

    if @message.is_system_notification != 1
      @id = []
      @id << @message.user_id.to_s && @id << @message.to_user_id.to_s
      if !@id.include?(@current_user.id.to_s)
        return redirect_to "/contact_us"
      end
    else
      @to_user_id_array = @message.to_user_id.split(",")
      if !@to_user_id_array.include?(@current_user.id.to_s)
        return redirect_to "/contact_us"
      end
    end


  end

  # GET /messages/new
  def new
    @user = User.all
    @message = @current_user.messages.new
    @email_list = ["All"]
    @user.each do |u|
      @email_list << u.email
    end

    @reply_message_id = params[:reply_message_id]
    @reply_user_id = params[:reply_user_id]
    @reply_user_email = params[:reply_user_email]
    @reply_subject = params[:reply_subject]
    @reply_content = params[:reply_content]
    # data = {:message => @reply_user_email, :status => "false"}
    # return render :json => data, :status => :ok
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = @current_user.messages.new(message_params)
    @message.from_email = @current_user.email

    if @message.subject.to_s == "" && @message.content.to_s == ""
        return redirect_to "/new_message", alert: "You can not send an empty message."
    end

    if !@current_user.admin?
      @message.to_user_id = "1"
      @message.email = "admin@parrot66.com"

      respond_to do |format|
        if @message.save
          # @message.update_attribute(:parent_id, @message.id)
          format.html { redirect_to "/contact_us", notice: 'Your messages has been sent.' }
          # format.json { render :show, status: :created, location: @message }
        else
          format.html { render :new }
          # format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    else
      @user = User.all
      @to_user_id_list = []
      @user.each do |u|
        @to_user_id_list << u.id.to_s
      end
      @to_user_id_list = @to_user_id_list.join(",")

      if @message.email == "All"
        @message.is_system_notification = 1
        @message.to_user_id = @to_user_id_list

        @user.each do |u|
          mg_client = Mailgun::Client.new("key-e55d9349c3a7816034d2dab0ae5b8808")
          mb_obj = Mailgun::MessageBuilder.new()

          mb_obj.set_from_address("do-not-reply@parrot.com", {"first"=>"Parrot 66", "last" => ""});
          mb_obj.add_recipient(:to, u.email, {"first"=> u.f_name.to_s, "last" => u.l_name.to_s});
          mb_obj.set_subject("P66 | New message notification");

          result_msg = "<p>Dear "+u.f_name.to_s+" "+u.l_name.to_s+"</p>"
          result_msg += "<p>you have a new message from Parrot66<br />"
          result_msg += "please check your user account.</p>"
          result_msg += "<p></p>"
          result_msg += "<p>Best regards,</p>"

          mb_obj.set_html_body(result_msg);
          mg_client.send_message("parrot66.com", mb_obj)
        end

      else
        @receive_user = User.find_by_email(@message.email)
        @message.to_user_id = @receive_user.id.to_s

        mg_client = Mailgun::Client.new("key-e55d9349c3a7816034d2dab0ae5b8808")
        mb_obj = Mailgun::MessageBuilder.new()

        mb_obj.set_from_address("do-not-reply@parrot.com", {"first"=>"Parrot 66", "last" => ""});
        mb_obj.add_recipient(:to, @receive_user.email, {"first"=> @receive_user.f_name.to_s, "last" => @receive_user.l_name.to_s});
        mb_obj.set_subject("P66 | New message notification");

        result_msg = "<p>Dear "+@receive_user.f_name.to_s+" "+@receive_user.l_name.to_s+"</p>"
        result_msg += "<p>you have a new message from Parrot66<br />"
        result_msg += "please check your user account.</p>"
        result_msg += "<p></p>"
        result_msg += "<p>Best regards,</p>"

        mb_obj.set_html_body(result_msg);
        mg_client.send_message("parrot66.com", mb_obj)
      end

      respond_to do |format|
        if @message.save
          # @message.update_attribute(:parent_id, @message.id)
          format.html { redirect_to "/contact_us", notice: 'Your messages has been sent.' }
          # format.json { render :show, status: :created, location: @message }
        else
          format.html { render :new }
          # format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def reply
    @reply_message_id = params[:reply_message_id]
    @reply_user_id =  params[:reply_user_id]
    @reply_user_email = params[:reply_user_email]
    @reply_subject = params[:reply_subject]
    @reply_content = params[:reply_content]

    if @reply_content == ""
      return redirect_to :back, alert: "You can not send an empty message."
    end

    # @parent = Message.find_by_id(@reply_message_id)
    @message = @current_user.messages.new(:parent_id => @reply_message_id)

    @message.to_user_id = @reply_user_id
    @message.email = @reply_user_email
    @message.from_email = @current_user.email
    @message.subject = @reply_subject
    @message.content = @reply_content

    # data = {:message => Message.children, :status => "false"}
    # return render :json => data, :status => :ok

    if !@current_user.admin?
      @message.email = "admin@parrot66.com"
      respond_to do |format|
        if @message.save
          format.html { redirect_to "/contact_us", notice: 'Your messages has been sent.' }
          # format.json { render :show, status: :created, location: @message }
        else
          format.html { render :new }
          # format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end

    # data = {:message => params[:reply_user_email], :status => "false"}
    # return render :json => data, :status => :ok

    # redirect_to new_message_path(reply_message_id: params[:reply_message_id], reply_user_id: params[:reply_user_id], reply_user_email: params[:reply_user_email], reply_subject: params[:reply_subject], reply_content: params[:reply_content])
    else
      @receive_user = User.find_by_email(@reply_user_email)
      mg_client = Mailgun::Client.new("key-e55d9349c3a7816034d2dab0ae5b8808")
      mb_obj = Mailgun::MessageBuilder.new()

      mb_obj.set_from_address("do-not-reply@parrot.com", {"first"=>"Parrot 66", "last" => ""});
      mb_obj.add_recipient(:to, @receive_user.email, {"first"=> @receive_user.f_name.to_s, "last" => @receive_user.l_name.to_s});
      mb_obj.set_subject("P66 | New message notification");

      result_msg = "<p>Dear "+@receive_user.f_name.to_s+" "+@receive_user.l_name.to_s+"</p>"
      result_msg += "<p>you have a new message from Parrot66<br />"
      result_msg += "please check your user account.</p>"
      result_msg += "<p></p>"
      result_msg += "<p>Best regards,</p>"

      mb_obj.set_html_body(result_msg);
      mg_client.send_message("parrot66.com", mb_obj)

      respond_to do |format|
        if @message.save
          format.html { redirect_to "/contact_us", notice: 'Your messages has been sent.' }
          # format.json { render :show, status: :created, location: @message }
        else
          format.html { render :new }
          # format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        # format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        # format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete
    @box =  params[:box]
    @message_id = params[:message_id]
    @user_id = params[:user_id]
    @to_user_id = params[:to_user_id]

    @user = User.all
    @to_user_id_list = []
    @user.each do |u|
      @to_user_id_list << u.id.to_s
    end
    @to_user_id_list = @to_user_id_list.join(",")

    @delete_message = Message.where(:id => @message_id)
    if !@delete_message.empty?
      @delete_message.each do |d|
        if d.is_system_notification == 1
          if @box == "inbox"
            @delete_user_id_list = @to_user_id_list.split(",")
            @delete_user_id_list -= [@to_user_id]
            @delete_user_id_list = @delete_user_id_list.join(",")
            d.update_attribute(:to_user_id, @delete_user_id_list)
            # data = {:message => d, :status => "false"}
            # return render :json => data, :status => :ok
          elsif @box == "sendbox"
            d.update_attribute(:user_id, "")
          end
          # if @delete_user_id_list == []
          #   d.destroy
          # end
        else
          if @box == "inbox"
            d.update_attribute(:to_user_id, "")
          elsif @box == "sendbox"
            d.update_attribute(:user_id, "")
          end

          # if d.to_user_id == "" || d.user_id == ""
          #   d.destroy
          # end
        end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_bmr_select.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/_inbox_message.html.erb
<table class="tb-inbox">
  <thead class="th-user">
    <tr>
      <th><%= check_box_tag 'check-all-inbox' %></th>
      <th>Subject</th>
      <th>Content</th>
      <th></th>
      <th>From</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @inbox_messages.each do |message| %>
      <% if message.to_user_id != @current_user.id.to_s %>
        <% to_user_id_array = message.to_user_id.split(",") %>
        <% if to_user_id_array.include?(@current_user.id.to_s) %>
          <tr class="clickable-row" date-link='<%= link_to '', message_path(message), :class => 'link-to-mail' %>'>
            <td class="checkbox-td">
              <%= check_box_tag 'inbox_message', message.id %>
              <%= hidden_field_tag 'box', 'inbox' %>
            </td>
            <td><%= message.subject %></td>
            <td class="JQellipsis"><%= message.content %></td>
            <td><%= link_to '', message_path(message), :class => "link-to-mail" %></td>
            <td><%= message.from_email %></td>
            <td><%= message.created_at %></td>
          </tr>
        <% end %>
      <% else %>
        <tr  class="clickable-row" date-link='<%= link_to '', message_path(message), :class => 'link-to-mail' %>'>
          <td class="checkbox-td">
            <%= check_box_tag 'inbox_message', message.id %>
            <%= hidden_field_tag 'box', 'inbox' %>
          </td>
          <td><%= message.subject %>
          <td class="JQellipsis"><%= message.content %></td>
          <td><%= link_to '', message_path(message), :class => "link-to-mail" %></td>
          <td><%= message.from_email %></td>
          <td><%= message.created_at %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= javascript_include_tag "js/messages.js" %>

app/views/messages/_sendbox_message.html.erb
<table class="tb-inbox">
  <thead class="th-user">
    <th><%= check_box_tag 'check-all-sendbox' %></th>
    <th>Subject</th>
    <th>Content</th>
    <th></th>
    <th>From</th>
    <th>Date</th>
  </thead>
  <tbody>
    <% @sendbox_messages.each do |message| %>
      <tr class="clickable-row" date-link='<%= link_to '', message_path(message), :class => 'link-to-mail' %>'>
        <td class="checkbox-td">
          <%= check_box_tag 'sendbox_message', message.id  %>
          <%= hidden_field_tag 'box', 'sendbox' %>
        </td>
        <td><%= message.subject %></td>
        <td class="JQellipsis"><%= message.content %></td>
        <td><%= link_to '', message_path(message) , :class => "link-to-mail" %></td>
        <td><%= message.from_email %></td>
        <td><%= message.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= javascript_include_tag "js/messages.js" %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%=render "/users/header" %>

<div class="container-fluid">
  <div class="row" id="content-outter">
    <%=render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">
        <div class="contact-us">
          <div class="row">
            <% if notice %>
              <p id="notice"><%= notice %></p>
            <% end %>
            <!-- <p id="notice"><%= notice %></p> -->
            <div class="h1-style-user">Contact Us</div>
          </div>
          <div class="row">
            <ul class="nav nav-tabs ">
              <li class="active contact-btn-left">
                <a href="#inbox" class="btn btn-user-fade" data-toggle="tab" id="inbox-btn">
                  Inbox
                </a>
              </li>
              <li class="contact-btn-left">
                <a href="#sendbox" class="btn btn-user-fade" data-toggle="tab" id="sendbox-btn">
                  Sendbox
                </a>
              </li>

              <li class="contact-btn-right">
                <button type="button" class="btn btn-user-delete" id="delete">DELETE</button>
              </li>
              <li class="contact-btn-right">
                <%= link_to 'New Message', new_message_path, :class => "btn-user" %>
              </li>
            </ul>
          </div>
          <div class="row">
            <div class="tab-content">
              <div id="inbox" class="tab-pane fade in active">
                <%= render "inbox_message" %>
              </div>
              <div id="sendbox" class="tab-pane fade">
                <%= render "sendbox_message" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%=render "/users/footer" %>

<script>
$('#inbox-btn').click(function () {
  box = null;
  message_id = [];
  user_id = null;
  to_user_id = null;
  $('input:checkbox').prop('checked', false);
  $('#inbox').load('/inbox_reload');
});
$('#sendbox-btn').click(function () {
  box = null;
  message_id = [];
  user_id = null;
  to_user_id = null;
  $('input:checkbox').prop('checked', false);
  $('#sendbox').load('/sendbox_reload');
});

  $('#delete').click(function (e) {
    if ($(':checkbox:checked')) {
      var box = $($(':checkbox:checked')).next('input[type=hidden]').val();
      var message_id = [];
      var to_user_id = "";
      var user_id = "";
      $(':checkbox:checked').each(function (i) {
        message_id[i] = $(this).val();
      });
      if (box == 'inbox') {
        to_user_id = <%= @current_user.id %>;

      } else if (box == 'sendbox') {
        user_id = <%= @current_user.id %>;
      }
    }
    if(!$('input[type=checkbox]').is(':checked')){
      e.preventDefault();
      return false;
      // this.style.pointEvents = 'none';
        // $(this).addClass('pointer-events');
    }

    // console.log(box) console.log(message_id) console.log(user_id) box = null; message_id = []; user_id = null;
    $('input:checkbox').prop('checked', false);

    $.post("/message_delete", {
      box: box,
      message_id: message_id,
      user_id: user_id,
      to_user_id: to_user_id
    }, function (data, status) {
      if (data.status == "false") {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
        return;
      } else {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
      }
    });
  });
    $(document).ready(function () {
  if(!$("input[name='inbox_message']").is(':checked')){
      // $('#check-all-inbox').prop("checked", false);
  }
});
</script>

app/views/messages/new.html.erb
<%=render "/users/header" %>
<div class="container-fluid">
  <div class="row" id="content-outter">
    <%=render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">

        <div class="new-msg">
          <div class="col-md-6">
          <div class="h1-style-user">Contact Us</div>
          <%= link_to 'Back to Inbox', messages_path, :class => "btn btn-user" %>
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= simple_form_for @message do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <% if @current_user.admin? %>
                <label>To</label>
                <%= f.input :email, include_blank: false, :label => false, collection: @email_list %>
              <% end %>
              <div class="clearfix"></div>
              <label>Subject</label>
              <%= f.input :subject, :label => false %>
              <div class="clearfix"></div>
              <label>Message</label>
              <%= f.input :content, :as => :text, :label => false %>
              <div class="clearfix"></div>
              <span id="send_error_msg" style="color:red;"></span>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Send", :class => "btn-user", :id => "send" %>
              <button type="button" class="btn btn-user-fade" id="discard">Reset</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<%=render "/users/footer" %>
<%= javascript_include_tag "js/messages.js" %>

app/views/messages/show.html.erb
<%= render "/users/header" %>

<div class="container-fluid">
  <div class="row" id="content-outter">
    <%= render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">
        <div class="contact-us-mail content-inner">
          <div class="row container-fluid">
            <div class="h4-style-user"><%= @message.subject %></div>
            <%= link_to 'Back to Inbox', messages_path, :class => "btn btn-user" %>
            <button type="button" class="btn btn-user" id="trash-mail">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
          </div>
          <div class="msg-content">
            <% if @message.parent %>
              <% @message.ancestors.each do |message| %>
                <div class="msg-row">
                  <h2 class="no-display"><%= message.subject %></h2>
                  <div class="create-date"><%= message.created_at %></div>
                  <div class="message-content"><%= message.content %></div>
                </div>
              <% end %>
            <% end %>
            <div class="msg-row">
              <div class="create-date"><%= @message.created_at %></div>
              <div class="message-content"><%= @message.content %></div>
            </div>
          </div>
        <% if @message.user_id.to_s != @current_user.id.to_s %>
        <div class="row container-fluid">
          <div class="msg-reply">
          <form>
            <div class="form-group">
              <input type="hidden" class="" id="reply_user_email" aria-describedby="checkout" value="<%= @message.email %>">
              <input type="hidden" class="" id="reply_subject" aria-describedby="checkout" value="Re: <%= @message.subject %>">
              <textarea type="text" class="" id="reply_content" aria-describedby="checkout" name="reply_content"  placeholder="Your Message"></textarea>
            </div>
          </form>
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <span id="reply_error_msg" style="color:red;"></span>
          <button type="button" class="btn btn-user" id="reply">Send</button>
          <button type="button" class="btn btn-user" id="discard">Discard</button>
        </div>
        <% end %>
        </div>
        </div>

        </div>
      </div>
    </div>
  </div>
</div>

<%=render "/users/footer" %>
<!-- <p id="notice"><%= notice %></p> -->
<!-- <%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %> -->


<script>
// delete message
  $('#trash-mail').click(function(){
    var system_notification = <%= @message.is_system_notification %>;
    var message_id = <%= @message.id %>;
    var user_id = <%= @message.user_id.to_i %>;
    var current_user = <%= @current_user.id %>;
    var to_user_id = "";
    if (system_notification == 1) {
      to_user_id = current_user;
    }else {
      to_user_id = <%= @message.to_user_id.to_i %>;
    }
    var box = "";
    if (user_id == current_user) {
      box = "sendbox";
    }else {
      box = "inbox";
    }
    // console.log(system_notification);
    // console.log(to_user_id);

    $.post("/message_delete", {
      box: box,
      message_id: message_id,
      user_id: user_id,
      to_user_id: to_user_id
    }, function (data, status) {
      if (data.status == "false") {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
        return;
      } else {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
      }
    });
  });

// reply message
  $('#reply').click(function () {
    var reply_message_id = "<%= @message.id %>";
    var reply_user_id = "<%= @message.user_id %>";
    var reply_user_email = $("#reply_user_email").val();
    var reply_subject = $("#reply_subject").val();
    var reply_content = $("#reply_content").val();
    if (reply_content == "") {
      $( "#reply_error_msg" ).append( "<p style='color:red;'>Can not send an empty message</p>" );
      return;
    }
    // console.log(reply_subject)

    $.post("/message_reply", {
      reply_message_id: reply_message_id,
      reply_user_id: reply_user_id,
      reply_user_email: reply_user_email,
      reply_subject: reply_subject,
      reply_content: reply_content
    }, function (data, status) {
      if (data.status == "false") {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
        return;
      } else {
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
      }
    });
  });


</script>
<%= javascript_include_tag "js/messages.js" %>