config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :homes
  resources :contacts, only: [:new, :create]
  resources :users, only: [:index, :new, :create, :update, :show, :destroy]
  resources :messages, only: [:update, :show, :edit, :destroy]
  resources :tests , except: [:update]
  #PDF feature
  resources :invoices, only: [:index, :show]
  resources :invoices, only: [:index, :show] do
    resource :download, only: [:show]
  end

  # resources :carts do
  #   collection do
  #     delete :clean
  #   end
  # end
  # resources :items, controller: 'cart_items'
  resources :payment_records
  resources :payout_records
  resources :test_records
  resources :qars
  resources :prompts
  resources :responses

  delete 'logout'  => 'sessions#destroy'
  get '/resendtokenpage' => 'application#resendtokenpage'
  post '/resendtoken' => 'application#resendtoken'
  get '/resendtokensuccessful' => 'application#resendtokensuccessful'

  get '/activeuser' => 'application#activeuser'

  post '/forget_email' => 'application#forget_email'
  post '/forget_password' => 'application#forget_password'

  get '/resetpassword' => 'application#getresetpassword'
  post '/resetpassword' => 'application#postresetpassword'

  get '/resetpasswordsuccessful' => 'application#resetpasswordsuccessful'


  match '/login' => 'users#login', :via => [:post, :get]
  match '/logout' => 'users#logout', :via => [:post, :get]

  get '/thankyou' => 'homes#thankyou'

  get '/active_link_done' => 'homes#active_link_done'
  get '/active_link_fail' => 'homes#active_link_fail'

  # homes inner pages routes
  # get '/howitworks' => 'homes#howitworks'
  # get '/aboutthetests' => 'homes#aboutthetests'
  # get '/aboutparrot' => 'homes#aboutparrot'
  # get '/parrotforbusiness' => 'homes#parrotforbusiness'
  # get '/howtobecomeaparrotrater' => 'homes#howtobecomeaparrotrater'
  # get '/contactus' => 'homes#contactus'
  # get '/test' => 'homes#testtemplate'
  # get '/faq' => 'homes#faq'
  # get '/privatepolicy' => 'homes#privatepolicy'
  get '/test_introduction/:id(.:format)' => 'homes#test_introduction', :as => 'test_introduction'
  match '/search_tests' => 'homes#search_tests', :via => [:post, :get]
  get '/notfound' => 'application#not_found'



  # cart
  # post '/save_item' => 'tests#save_item'
  post '/add_to_cart' => 'tests#add_to_cart'
  get '/cart_number_reload' => 'homes#cart_number_reload'
  get '/cart' => 'carts#cart'
  post '/delete_item' => 'carts#delete_item'
  post '/clean_cart' => 'carts#clean_cart'
  post '/cart_login' => 'carts#cart_login'

  # payment
  get '/checkout' => 'paypals#new'
  post '/checkout_with_credit_card' => 'paypals#checkout_with_credit_card'
  post '/checkout_with_paypal' => 'paypals#checkout_with_paypal'
  get '/thankyoupurchase' => 'paypals#thankyoupurchase'
  post '/cancel_order' => 'paypals#cancel_order'
  get '/payout_new' => 'paypals#payout_new'
  match '/payout_create' => 'paypals#payout_create', :via => [:post, :get]
  get '/payment_pdf' => 'payment_records#download_payment_pdf'


  # admin home
  get '/dashboard' => 'users#dashboard'
  get '/cashflow' => 'users#cashflow'
  get '/invite' => 'users#invite'
  post '/invite_user' => 'users#invite_user'
  post '/invite_as_rater' => 'users#invite_as_rater'
  get '/cheating/:id(.:format)' => 'users#cheating', :as => 'cheating'
  post '/change_user_status' => 'users#change_user_status'

  # cms
  get '/cms' => 'users#cms'
  get '/cms/:id/edit(.:format)' => 'users#page_edit', :as => 'page_edit'
  post '/tinymce_assets' => 'users#upload_image'
  put '/cms/content_update/:id(.:format)' => 'users#content_update', :as => 'content_update'

  # user home
  get '/home' => 'users#home'
  get '/account' => 'users#edit', :as => 'edit_user'
  get '/payment' => 'payment_records#index'
  get '/test_brief/:id(.:format)' => 'tests#test_brief', :as => 'test_brief'
  post '/test_checkout' => 'tests#test_checkout'
  # get '/prompts' => 'users#prompts'
  # post '/change_password' => 'users#change_password'
  get '/certificate_pdf' => 'users#download_certificate_pdf'

  # rater home
  get '/rating_history' => 'users#rating_history'

  # test
  put '/tests/:id(.:format)' => 'tests#update', :as => 'test_update'
  get '/sendscores' => 'test_records#sendscores'
  get '/score_histiry' => 'test_records#score_histiry'
  post '/send_response' => 'tests#send_response'
  post '/close_test' => 'tests#close_test'
  get '/finished_test' => 'tests#finished_test'
  # get '/test_begin_camera' => 'test_records#test_begin_camera'
  post '/post_test_begin_photo' => 'test_records#post_test_begin_photo'
  # get '/test_end_camera' => 'test_records#test_end_camera'
  post '/post_test_end_photo' => 'test_records#post_test_end_photo'
  post '/window_lose_focus' => 'tests#window_lose_focus'
  post '/take_practice_test/:id(.:format)' => 'tests#take_practice_test', :as => 'take_practice_test'

  # response
  post '/change_response_type' => 'responses#change_response_type'
  post '/audio_record_create' => 'responses#audio_record_create'
  get '/rater_available' => 'responses#rater_available'
  get '/photo_verification/:id(.:format)' => 'test_records#photo_verification', :as => 'photo_verification'
  post '/post_photo_verification' => 'test_records#post_photo_verification'
  get '/rate_response/:id(.:format)' => 'responses#rate_response', :as => 'rate_response'
  match '/give_a_rate' => 'responses#give_a_rate', :via => [:post, :get]
  post '/test_answer' => 'responses#test_answer'
  # get '/recorder' => 'responses#recorder'
  post '/qar_submit' => 'qars#qar_submit'

  # Contact us
  get '/contact_us' => 'messages#index', :as => 'messages'
  get '/new_message' => 'messages#new', :as => 'new_message'
  post '/contact_us' => 'messages#create'
  post '/message_delete' => 'messages#delete'
  post '/message_reply' => 'messages#reply'
  get '/inbox_reload' => 'messages#inbox_reload'
  get '/sendbox_reload' => 'messages#sendbox_reload'


  get '/:slug' => 'homes#find_page'
  # get '*slug' => 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qar.rb
class Qar < ApplicationRecord
end

app/controllers/qars_controller.rb
class QarsController < ApplicationController
  before_action :set_qar, only: [:show, :edit, :update, :destroy]
  before_action :authuser

  # GET /qars
  # GET /qars.json
  def index
    @qars = Qar.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /qars/1
  # GET /qars/1.json
  def show
    if !@current_user.rater? && !@current_user.admin?
      return redirect_to "/home"
    end

    @qar = Qar.find(params[:id])

    if !@qar.raters.nil? && @qar.raters.include?(@current_user.id.to_s)
      return redirect_to "/rater_available", :notice => "The response has been rated."
    end

    @qar.lock!


    @prompt = Prompt.find_by_id(@qar.prompt.to_i)
    @bmr = Response.find_by_id(@qar.bmr.to_i)
    @response = Response.find_by_id(@qar.response.to_i)

  end

  def qar_submit
    @qar = Qar.find_by_id(params[:qar_id])
    @rating = params[:rating]
    @rater_id = @current_user.id

    if @rating == "0"
        return redirect_to qar_path(@qar), alert: "Please select a rating"
    end

    case @rating
    when "better than"
      if @qar.rating == "worse than"
        if @current_user.qar_fails.nil?
          @current_user.update_attribute(:qar_fails, 1)
        else
          @qar_fails = @current_user.qar_fails + 1
          @current_user.update_attribute(:qar_fails, @qar_fails)
        end
      end
    when "as good as"
      if @qar.rating == "worse than"
        if @current_user.qar_fails.nil?
          @current_user.update_attribute(:qar_fails, 1)
        else
          @qar_fails = @current_user.qar_fails + 1
          @current_user.update_attribute(:qar_fails, @qar_fails)
        end
      end
    when "worse than"
      if @qar.rating == "better than" || @qar.rating == "as good as"
        if @current_user.qar_fails.nil?
          @current_user.update_attribute(:qar_fails, 1)
        else
          @qar_fails = @current_user.qar_fails + 1
          @current_user.update_attribute(:qar_fails, @qar_fails)
        end
      end
    end

    @raters = @qar.raters.split(",").map(&:to_i)
    @raters << @rater_id
    @raters = @raters.join(",")
    @qar.update_attribute(:raters, @raters)

    @total_rated = @current_user.total_rated + 1
    @current_user.update_attribute(:total_rated, @total_rated)

    if @current_user.qar_fails == 2
      mg_client = Mailgun::Client.new("key-e55d9349c3a7816034d2dab0ae5b8808")
      mb_obj = Mailgun::MessageBuilder.new()

      mb_obj.set_from_address("do-not-reply@parrot.com", {"first"=>"Parrot 66", "last" => ""});
      mb_obj.add_recipient(:to, @current_user.email, {"first"=> @current_user.f_name.to_s, "last" => @current_user.l_name.to_s});
      mb_obj.set_subject("P66 | Warning ! ! !");

      result_msg = "<p>Dear "+@current_user.f_name.to_s+" "+@current_user.l_name.to_s+"</p>"
      result_msg += "<p>Be Careful, you have reached the maximum times of QA fails.<br />"
      result_msg += "you will lose ability to rate responses if the QA failed again.</p>"
      result_msg += "<p></p>"
      result_msg += "<p>Best regards,</p>"

      mb_obj.set_html_body(result_msg);
      mg_client.send_message("parrot66.com", mb_obj)
    elsif @current_user.qar_fails == 3
      mg_client = Mailgun::Client.new("key-e55d9349c3a7816034d2dab0ae5b8808")
      mb_obj = Mailgun::MessageBuilder.new()

      mb_obj.set_from_address("do-not-reply@parrot.com", {"first"=>"Parrot 66", "last" => ""});
      mb_obj.add_recipient(:to, @current_user.email, {"first"=> @current_user.f_name.to_s, "last" => @current_user.l_name.to_s});
      mb_obj.set_subject("P66 | Warning ! ! !");

      result_msg = "<p>Dear "+@current_user.f_name.to_s+" "+@current_user.l_name.to_s+"</p>"
      result_msg += "<p>You have exceeded the maximum times of QA fails.<br />"
      result_msg += "you can't rate responses no longer.</p>"
      result_msg += "<p></p>"
      result_msg += "<p>Best regards,</p>"

      mb_obj.set_html_body(result_msg);
      mg_client.send_message("parrot66.com", mb_obj)

      @current_user.update_attribute(:is_rater, 0)
    end

    redirect_to '/rater_available', notice: "Rating Success!"

  end

  # GET /qars/new
  def new
    if !@current_user.admin?
      return redirect_to '/home'
    end

    @qar = Qar.new

    # prompt select
    @prompts = Prompt.all

    @all_prompt_hash = {}
    @all_lang_prompt_hash = {}
    @all_industry_prompt_hash = {}
    @all_level_prompt_hash = {}

    if @prompts.count.to_i > 0
        @prompts.each do |prompt|
            @all_prompt_hash[prompt["id"]] = prompt

            if @all_lang_prompt_hash[prompt["language"]].nil?
                @all_lang_prompt_hash[prompt["language"]] = []
            end

            if @all_industry_prompt_hash[prompt["industry"]].nil?
                @all_industry_prompt_hash[prompt["industry"]] = []
            end

            if @all_level_prompt_hash[prompt["level"]].nil?
                @all_level_prompt_hash[prompt["level"]] = []
            end

            @all_lang_prompt_hash[prompt["language"]] << prompt["id"]
            @all_industry_prompt_hash[prompt["industry"]] << prompt["id"]
            @all_level_prompt_hash[prompt["level"]] << prompt['id']
        end

        # data = { :message => @all_prompt_hash, :status => "false"}
        # return render :json => data, :status => :ok
    end


    # bmr select
    @bmrs = Response.where(:response_type => 1)

    @all_bmr_hash = {}
    @all_lang_bmr_hash = {}
    @all_industry_bmr_hash = {}
    @all_level_bmr_hash = {}

    if @bmrs.count.to_i > 0
        @bmrs.each do |bmr|
            @all_bmr_hash[bmr["id"]] = bmr

            if @all_lang_bmr_hash[bmr["language"]].nil?
                @all_lang_bmr_hash[bmr["language"]] = []
            end

            if @all_industry_bmr_hash[bmr["industry"]].nil?
                @all_industry_bmr_hash[bmr["industry"]] = []
            end


            if @all_level_bmr_hash[bmr["level"]].nil?
                @all_level_bmr_hash[bmr["level"]] = []
            end

            @all_lang_bmr_hash[bmr["language"]] << bmr["id"]
            @all_industry_bmr_hash[bmr["industry"]] << bmr["id"]
            @all_level_bmr_hash[bmr["level"]] << bmr["id"]
        end
    end


    # response select
    @responses = Response.where(:response_type => 0)

    @all_response_hash = {}
    @all_lang_response_hash = {}
    @all_industry_response_hash = {}
    @all_level_response_hash = {}

    if @responses.count.to_i > 0
        @responses.each do |response|
            @all_response_hash[response["id"]] = response

            if @all_lang_response_hash[response["language"]].nil?
                @all_lang_response_hash[response["language"]] = []
            end

            if @all_industry_response_hash[response["industry"]].nil?
                @all_industry_response_hash[response["industry"]] = []
            end


            if @all_level_response_hash[response["level"]].nil?
                @all_level_response_hash[response["level"]] = []
            end

            @all_lang_response_hash[response["language"]] << response["id"]
            @all_industry_response_hash[response["industry"]] << response["id"]
            @all_level_response_hash[response["level"]] << response["id"]
        end
    end

  end

  # GET /qars/1/edit
  def edit
    @qar = Qar.find(params[:id])
  end

  # POST /qars
  # POST /qars.json
  def create
    @qar = Qar.new(qar_params)

    if @qar.title.to_s == "" || @qar.language.to_s == "" || @qar.industry.to_s == "" || @qar.level.to_s == "" || @qar.prompt.to_s == "" || @qar.bmr.to_s == "" || @qar.response.to_s == "" || @qar.rating.to_s == ""
      return redirect_to new_qar_path, notice: "Please fill in all required fields"
    end

    respond_to do |format|
      if @qar.save
        format.html { redirect_to qars_path, notice: 'Qar was successfully created.' }
        format.json { render :show, status: :created, location: @qar }
      else
        format.html { render :new }
        format.json { render json: @qar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qars/1
  # PATCH/PUT /qars/1.json
  def update
    @qar = Qar.find(params[:id])

    respond_to do |format|
      if @qar.update(qar_params)
        format.html { redirect_to qars_path, notice: 'Qar was successfully updated.' }
        format.json { render :show, status: :ok, location: @qar }
      else
        format.html { render :edit }
        format.json { render json: @qar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qars/1
  # DELETE /qars/1.json
  def destroy
    @qar.destroy
    respond_to do |format|
      format.html { redirect_to qars_url, notice: 'Qar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qar
      @qar = Qar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qar_params
      params.fetch(:qar, {})

      params.require(:qar).permit(:title, :language, :industry, :level, :prompt, :bmr, :response, :rating)
    end
end

app/helpers/qars_helper.rb
module QarsHelper
end

app/views/qars/_form.html.erb
<%= simple_form_for(@qar) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/qars/index.html.erb
<%=render "/users/header" %>
<div class="container-fluid">
  <div class="row" id="content-outter">
    <%=render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">
        <div class="contact-us">
          <div class="row">
            <% if notice %>
              <p id="notice"><%= notice %></p>
            <% end %>
            <div class="h1-style-user">QAR</div>
          </div>
          <div class="row">
            <div class="col-md-6 flex">
              <%= link_to 'Create QAR', new_qar_path, :class => 'btn btn-user-link flex-item' %>
              <!-- <div class="input-group stylish-input-group tests-search flex-item">
                    <input type="text" class="form-control">
                    <span class="input-group-addon">
                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div> -->
              <!-- <button type="button" name="button" class="btn btn-user-icon flex-item"><i class="fa fa-filter" aria-hidden="true"></i></button> -->
              </div>
              <div class="col-md-6 text-right flex-end">
                <!-- <div class="page-number flex-item">1 - 15 of 42</div>
                <div class="btn btn-user-icon flex-item"><i class="fa fa-chevron-left" aria-hidden="true"></i></div>
                <div class="btn btn-user-icon flex-item"><i class="fa fa-chevron-right" aria-hidden="true"></i></div> -->
                <%= will_paginate @qars, renderer: 'PaginateHelper::LinkRenderer' %>
              </div>
          </div>
          <div class="row">
            <table class="tb-admin-tests">
              <thead>
                <tr>
                  <th>QAR Titles</th>
                  <th>Language</th>
                  <th>Industry</th>
                  <th>Link Prompt</th>
                  <th>Link BMR</th>
                  <th>Link Response</th>
                  <th>Rating</th>
                  <th></th>
                  <!-- <th>Edit</th> -->
                  <th>Trash</th>
                </tr>
              </thead>

              <tbody>
                  <% @qars.each do |qar| %>
                  <tr>
                    <td><%= qar.title %></td>
                    <td><%= qar.language %></td>
                    <td><%= qar.industry %></td>

                    <% if Prompt.find_by_id(qar.prompt) %>
                    <td><%= Prompt.find_by_id(qar.prompt).title %></td>
                    <% else %>
                    <td><strong>Prompt LOST</strong></td>
                    <% end %>

                    <% if Response.find_by_id(qar.bmr) %>
                    <td><%= Response.find_by_id(qar.bmr).title %></td>
                    <% else %>
                    <td><strong>BMR LOST</strong></td>
                    <% end %>

                    <% if Response.find_by_id(qar.response) %>
                    <td><%= Response.find_by_id(qar.response).title %></td>
                    <% else %>
                    <td><strong>Response LOST</strong></td>
                    <% end %>

                    <td><%= qar.rating %></td>
                    <td></td>

                    <!-- <td><%= link_to edit_qar_path(qar) do %><i class="fa fa-pencil" aria-hidden="true"></i><% end %></td> -->
                    <td><%= link_to qar, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-trash" aria-hidden="true"></i><% end %></td>
                  </tr>
                  <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<%=render "/users/footer" %>
<script>
//sidebar
$("li.admin-prompts").addClass("active");
$("#qar").addClass("active");

</script>

app/views/qars/show.html.erb
<!-- take-test-header -->
<div class="header-user">
  <nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="test-title">Rating: <%= @qar.title %></div>
  </div>
  </nav>
</div>
<!-- take-test-body -->
<div class="rate-test">
  <div class="container">
    <div class="rate-test-inner">
      <div class="row">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <div class="row section-b">
        <div class="col-md-2"><%= image_tag ( "homepage/logo-86x85.png") %></div>
        <div class="col-md-4">
       </div>
      </div>
      <div class="section-b">
            <div class="questions">
              <div class="question_text">
                <%= @prompt.text.html_safe if !@prompt.text.nil? %>
              </div>
              <div class="test-video"><%= video_tag(@prompt.video, controls: true) unless @prompt.video.blank? %></div>
              <div class="test-audio"><%= audio_tag(@prompt.audio, controls: true) unless @prompt.audio.blank? %></div>
              <div><%= image_tag @prompt.image if @prompt.image %></div>
              <div class="flex">
                <div class="flex-item">
                  <div>The Bench Mark Response(BMR)</div>
                  <% if @bmr %>
                  <!--
                  <%= audio_tag(@bmr.avatar, controls: true, onended: "enableRadioButton()") %>
                  -->
                  <audio id="bmr" controls="controls" onended="checkBMR()" src="<%= @bmr.avatar %>"></audio>
                  <% else %>
                  <strong>BMR LOST</strong>
                  <% end %>
                  <!-- <button type="button" name="button" class="btn btn-user btn-bmr-response start-bmr" id="recorder_btn" onclick="startRecording();"><i class="fa fa-play-circle-o" aria-hidden="true"></i> Play Benchmark Response</button>
                  <button type="button" name="button" class="btn btn-user btn-bmr-response stop-bmr" onclick="stopRecording();"><i class="fa fa-stop-circle-o" aria-hidden="true"></i>Stop Benchmark Response<div class="loading"><span></span><span></span><span></span></div></button> -->
                </div>

              <div class="flex-item">
                <div>Candidate Response</div>
                <!--
                <%= audio_tag(@response.avatar, controls: true,  onended: "enableBMR()") %>
                -->
                <audio id="cr" controls="controls" onended="checkCR()" src="<%= @response.avatar %>"></audio>
                <!-- <button type="button" name="button" class="btn btn-user btn-bmr-response start-cdnr" id="recorder_btn" onclick="startRecording();"><i class="fa fa-play-circle-o" aria-hidden="true"></i> Play Candidate Response</button>
                <button type="button" name="button" class="btn btn-user btn-bmr-response stop-cdnr" onclick="stopRecording();"><i class="fa fa-stop-circle-o" aria-hidden="true"></i> Stop Candidate Response<div class="loading"><span></span><span></span><span></span></div></button> -->
              </div>
            </div>
        </div>
          <div class="rating-test-section">
            <div class="cr-title">Rate the Candidate Response (CR)</div>
            <div class="cr-is">The Candidate Response(CR) is</div>
              <div class="cr-rating">
              <label class="radio-inline"><input type="radio" name="optradio" value="better than" disabled>better than</label>
              <label class="radio-inline"><input type="radio" name="optradio" value="as good as" disabled>as good as</label>
              <label class="radio-inline"><input type="radio" name="optradio" value="worse than" disabled>worse than</label>
              </div>
            <div class="cr-is">the Benchmark.</div>
          </div>
          <div class="flex">
        <div class="flex-item">  <button type="button" class="btn btn-user-fade" id="submit" disabled>Submit</button></div>
          <div class="flex-item"> <%= link_to 'Cancel', rater_available_path, :class=>"btn btn-user-fade" %></div>
          <span id="send_error_msg" style="color:red;">Please listen to BMR and CR before rating.</span>
         </div>
        </div>
      </div>
    </div>
  </div>

<%=render "/users/footer" %>

<script>

  var isBMRPlayed = false;
  var isCRPlayed = false;

  if ($("#bmr").length == 0) {
    console.log("No BMR");
    isBMRPlayed = true;
    checkRadioButton();
  }

  $("#bmr").on("error", function () {
    console.log("BMR Error");
    isBMRPlayed = true;
    checkRadioButton();
  });

  document.getElementById("bmr").onloadedmetadata = function() {
    //console.log("BMR: " + this.duration)
    if (this.duration == 0) {
      console.log("BMR 0");
      isBMRPlayed = true;
      checkRadioButton();
    }
  }

  if ($("#cr").length == 0) {
    console.log("No CR");
    isCRPlayed = true;
    checkRadioButton();
  }

  $("#cr").on("error", function () {
    console.log("CR Error");
    isCRPlayed = true;
    checkRadioButton();
  });

  document.getElementById("cr").onloadedmetadata = function() {
    //console.log("CR: " + this.duration)
    if (this.duration == 0) {
      console.log("CR 0");
      isCRPlayed = true;
      checkRadioButton();
    }
  }

  function checkBMR() {
    isBMRPlayed = true;
    checkRadioButton();
  }

  function checkCR() {
    //$.playSound("@bmr.avatar");
    isCRPlayed = true;
    checkRadioButton();
  }

  function checkRadioButton() {
    if(isBMRPlayed && isCRPlayed){
      $("input[type=radio]").attr('disabled', false);
    }
  }

$(function(){
  $('input[name=optradio]').change(function(){
    if ($(this).is(':checked')) {
       $('#submit').addClass('btn-submit-rate');
       $('#submit').attr('disabled', false);
       $('#send_error_msg').text('');
    }
  });
});

$('#submit').click(function() {

  var qar_id = <%= @qar.id %>;
  var rating = 0;

  if ($('[name="optradio"]:checked').length == 0) {
    rating = 0;


  }else {
    rating = $('input[name=optradio]:checked').val();
  }

  if(rating == 0 || confirm("You said the Candidate was " + $('[name="optradio"]:checked').val() + " the Benchmark - are you sure?")){
    $.ajax({
      url: '/qar_submit',
      type: 'post',
      data: {
        qar_id: qar_id,
        rating: rating
      },
      success: function() {console.log();},
      error: function() {console.log('error');}
    });
  }
});

// record-btn
$('.stop-bmr').click(function(){
  $('.start-bmr').toggle();
  $('.stop-bmr').toggle();
});
$( ".stop-bmr" ).hide();
$('.start-bmr').click(function(){
  $('.start-bmr').toggle();
  $('.stop-bmr').toggle();
});
$('.stop-cdnr').click(function(){
  $('.start-cdnr').toggle();
  $('.stop-cdnr').toggle();
});
$( ".stop-cdnr" ).hide();
$('.start-cdnr').click(function(){
  $('.start-cdnr').toggle();
  $('.stop-cdnr').toggle();
});

//stop 2 or more audios playing at the same time


document.addEventListener('play', function(e){
    var audios = document.getElementsByTagName('audio');
    for(var i = 0, len = audios.length; i < len;i++){
        if(audios[i] != e.target){
            audios[i].pause();
        }
    }
}, true);




// To remove audio player seeker



</script>