config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :homes
  resources :contacts, only: [:new, :create]
  resources :users, only: [:index, :new, :create, :update, :show, :destroy]
  resources :messages, only: [:update, :show, :edit, :destroy]
  resources :tests , except: [:update]
  #PDF feature
  resources :invoices, only: [:index, :show]
  resources :invoices, only: [:index, :show] do
    resource :download, only: [:show]
  end

  # resources :carts do
  #   collection do
  #     delete :clean
  #   end
  # end
  # resources :items, controller: 'cart_items'
  resources :payment_records
  resources :payout_records
  resources :test_records
  resources :qars
  resources :prompts
  resources :responses

  delete 'logout'  => 'sessions#destroy'
  get '/resendtokenpage' => 'application#resendtokenpage'
  post '/resendtoken' => 'application#resendtoken'
  get '/resendtokensuccessful' => 'application#resendtokensuccessful'

  get '/activeuser' => 'application#activeuser'

  post '/forget_email' => 'application#forget_email'
  post '/forget_password' => 'application#forget_password'

  get '/resetpassword' => 'application#getresetpassword'
  post '/resetpassword' => 'application#postresetpassword'

  get '/resetpasswordsuccessful' => 'application#resetpasswordsuccessful'


  match '/login' => 'users#login', :via => [:post, :get]
  match '/logout' => 'users#logout', :via => [:post, :get]

  get '/thankyou' => 'homes#thankyou'

  get '/active_link_done' => 'homes#active_link_done'
  get '/active_link_fail' => 'homes#active_link_fail'

  # homes inner pages routes
  # get '/howitworks' => 'homes#howitworks'
  # get '/aboutthetests' => 'homes#aboutthetests'
  # get '/aboutparrot' => 'homes#aboutparrot'
  # get '/parrotforbusiness' => 'homes#parrotforbusiness'
  # get '/howtobecomeaparrotrater' => 'homes#howtobecomeaparrotrater'
  # get '/contactus' => 'homes#contactus'
  # get '/test' => 'homes#testtemplate'
  # get '/faq' => 'homes#faq'
  # get '/privatepolicy' => 'homes#privatepolicy'
  get '/test_introduction/:id(.:format)' => 'homes#test_introduction', :as => 'test_introduction'
  match '/search_tests' => 'homes#search_tests', :via => [:post, :get]
  get '/notfound' => 'application#not_found'



  # cart
  # post '/save_item' => 'tests#save_item'
  post '/add_to_cart' => 'tests#add_to_cart'
  get '/cart_number_reload' => 'homes#cart_number_reload'
  get '/cart' => 'carts#cart'
  post '/delete_item' => 'carts#delete_item'
  post '/clean_cart' => 'carts#clean_cart'
  post '/cart_login' => 'carts#cart_login'

  # payment
  get '/checkout' => 'paypals#new'
  post '/checkout_with_credit_card' => 'paypals#checkout_with_credit_card'
  post '/checkout_with_paypal' => 'paypals#checkout_with_paypal'
  get '/thankyoupurchase' => 'paypals#thankyoupurchase'
  post '/cancel_order' => 'paypals#cancel_order'
  get '/payout_new' => 'paypals#payout_new'
  match '/payout_create' => 'paypals#payout_create', :via => [:post, :get]
  get '/payment_pdf' => 'payment_records#download_payment_pdf'


  # admin home
  get '/dashboard' => 'users#dashboard'
  get '/cashflow' => 'users#cashflow'
  get '/invite' => 'users#invite'
  post '/invite_user' => 'users#invite_user'
  post '/invite_as_rater' => 'users#invite_as_rater'
  get '/cheating/:id(.:format)' => 'users#cheating', :as => 'cheating'
  post '/change_user_status' => 'users#change_user_status'

  # cms
  get '/cms' => 'users#cms'
  get '/cms/:id/edit(.:format)' => 'users#page_edit', :as => 'page_edit'
  post '/tinymce_assets' => 'users#upload_image'
  put '/cms/content_update/:id(.:format)' => 'users#content_update', :as => 'content_update'

  # user home
  get '/home' => 'users#home'
  get '/account' => 'users#edit', :as => 'edit_user'
  get '/payment' => 'payment_records#index'
  get '/test_brief/:id(.:format)' => 'tests#test_brief', :as => 'test_brief'
  post '/test_checkout' => 'tests#test_checkout'
  # get '/prompts' => 'users#prompts'
  # post '/change_password' => 'users#change_password'
  get '/certificate_pdf' => 'users#download_certificate_pdf'

  # rater home
  get '/rating_history' => 'users#rating_history'

  # test
  put '/tests/:id(.:format)' => 'tests#update', :as => 'test_update'
  get '/sendscores' => 'test_records#sendscores'
  get '/score_histiry' => 'test_records#score_histiry'
  post '/send_response' => 'tests#send_response'
  post '/close_test' => 'tests#close_test'
  get '/finished_test' => 'tests#finished_test'
  # get '/test_begin_camera' => 'test_records#test_begin_camera'
  post '/post_test_begin_photo' => 'test_records#post_test_begin_photo'
  # get '/test_end_camera' => 'test_records#test_end_camera'
  post '/post_test_end_photo' => 'test_records#post_test_end_photo'
  post '/window_lose_focus' => 'tests#window_lose_focus'
  post '/take_practice_test/:id(.:format)' => 'tests#take_practice_test', :as => 'take_practice_test'

  # response
  post '/change_response_type' => 'responses#change_response_type'
  post '/audio_record_create' => 'responses#audio_record_create'
  get '/rater_available' => 'responses#rater_available'
  get '/photo_verification/:id(.:format)' => 'test_records#photo_verification', :as => 'photo_verification'
  post '/post_photo_verification' => 'test_records#post_photo_verification'
  get '/rate_response/:id(.:format)' => 'responses#rate_response', :as => 'rate_response'
  match '/give_a_rate' => 'responses#give_a_rate', :via => [:post, :get]
  post '/test_answer' => 'responses#test_answer'
  # get '/recorder' => 'responses#recorder'
  post '/qar_submit' => 'qars#qar_submit'

  # Contact us
  get '/contact_us' => 'messages#index', :as => 'messages'
  get '/new_message' => 'messages#new', :as => 'new_message'
  post '/contact_us' => 'messages#create'
  post '/message_delete' => 'messages#delete'
  post '/message_reply' => 'messages#reply'
  get '/inbox_reload' => 'messages#inbox_reload'
  get '/sendbox_reload' => 'messages#sendbox_reload'


  get '/:slug' => 'homes#find_page'
  # get '*slug' => 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  layout 'user'

  before_action :set_response, only: [:show, :edit, :update, :destroy]
  before_action :authuser, except: [:test_answer]

  # GET /responses
  # GET /responses.json
  def index
    if !@current_user.admin?
      return redirect_to '/home'
    end

    @responses = Response.paginate(:page => params[:page], :per_page => 25)
    #if(params[:title])
      #@responses = Response.where("title LIKE :title", {:title => "%#{params[:title]}%"}).paginate(:page => params[:page], :per_page => 25)
    #end
    if(params[:parrotid])
      #@userid = User.find_by_parrot_id(params[:parrotid]).id
      #@responses = Response.where("user_id LIKE :userid", {:userid => @userid}).paginate(:page => params[:page], :per_page => 25)
      logger.info "---------------------"
      logger.info @user = User.where("parrot_id LIKE :parrotid", {:parrotid => "%#{params[:parrotid]}%"}).as_json
      if @user.size > 0
      logger.info @userid = @user.first["id"]
      end
      logger.info @responses = Response.where("user_id LIKE :userid", {:userid => @userid}).paginate(:page => params[:page], :per_page => 25)
      logger.info "---------------------"
    end
    if(params[:firstname])
      #@userid = User.find_by_f_name(params[:firstname]).id
      #@responses = Response.where("user_id LIKE :userid", {:userid => @userid}).paginate(:page => params[:page], :per_page => 25)
      logger.info "---------------------"
      logger.info @user = User.where("f_name LIKE :fname", {:fname => "%#{params[:firstname]}%"}).as_json
      if @user.size > 0
      logger.info @userid = @user.first["id"]
      end
      logger.info @responses = Response.where("user_id LIKE :userid", {:userid => @userid}).paginate(:page => params[:page], :per_page => 25)
      logger.info "---------------------"
    end
    #if(params[:testid])
      #logger.info @userid = TestRecord.find_by_test_id(params[:testid]).user_id #only get the first userid now
      #@responses = Response.where("user_id LIKE :userid", {:userid => @userid}).paginate(:page => params[:page], :per_page => 25)
    #end
    # data = {:message => @response, :status => "false"}
    #  return render :json => data, :status => :ok
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
    @response = Response.find(params[:id])
  end

  # GET /responses/new
  def new
    if !@current_user.admin?
      return redirect_to '/home'
    end

    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
  end


  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    @response.user_id = @current_user.id

    if @response.title.to_s == "" || @response.language.to_s == "" || @response.industry.to_s == "" || @response.level.to_s == "" || @response.avatar.to_s == "" || @response.response_type.to_s == ""
        return redirect_to new_response_path, notice: "Please fill in all required fields"
    end

    # data = {:message => @response, :status => "false", :action => "create"}
    # return render :json => data, :status => :ok

    respond_to do |format|
      if @response.save
        format.html { redirect_to responses_path, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        # data = {:message => @response.errors, :status => "false"}
        # return render :json => data, :status => :ok
        # format.html { render :new }
        format.html { redirect_to new_response_path, notice: @response.errors }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def audio_record_create

    @response = Response.new

    @response.user_id = @current_user.id

    @response.avatar = params[:avatar]
    @response.title = params[:title]
    @response.language = params[:language]
    @response.industry = params[:industry]
    @response.level = params[:level]
    @response.response_type = params[:type]

    # data = {:message => @response, :status => "false", :action => "audio_record_create"}
    # return render :json => data, :status => :ok

    if @response.title.to_s == "" || @response.language.to_s == "" || @response.industry.to_s == "" || @response.level.to_s == "" || @response.avatar.to_s == "" || @response.response_type.to_s == ""
        return redirect_to new_response_path, notice: "Please fill in all required fields"
    end

    respond_to do |format|
      if @response.save
        format.html { redirect_to responses_path, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        # data = {:message => @response, :status => "false"}
        # return render :json => data, :status => :ok
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    @response = Response.find(params[:id])
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_response_type
    @response_type = params[:response_type]
    @response = Response.find_by_id(params[:response_id])

    @response.update_attribute(:response_type, @response_type)
      data = {:message => @response, :status => "false"}
      return render :json => data, :status => :ok
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # rating the test
  def rater_available

    if !@current_user.rater? && !@current_user.admin?
      return redirect_to "/home"
    end

    # @wait_for_verify = TestRecord.where(:photo_verification => 0, :status => 1)
    @complete_tests = TestRecord.where(:status => 1, :cheating => 0).group_by(&:photo_verification)

    @wait_for_verify_tests = @complete_tests[0]
    @verify_passed_tests = @complete_tests[1]

    # data = {:message => @verify_passed_tests, :status => "false"}
    # return render :json => data, :status => :ok

    @available_responses = []
    @english_responses = []
    @spanish_responses = []

    if !@verify_passed_tests.nil?

      @verify_passed_tests.each do |verify_passed_test|

        # data = {:message => verify_passed_test, :status => "false"}
        # return render :json => data, :status => :ok

        response = Response.where(:status => 0, :test_record_id => verify_passed_test.id).order("test_record_id asc, level desc").first

        # data = {:message => response, :status => "false"}
        # return render :json => data, :status => :ok

	if response
          if @prompt = Prompt.find_by_id(response.prompt_id)
            if @bmr = Response.find_by_id(@prompt.bmr)
            logger.info @prompt
            logger.info @bmr

          if response.raters.nil? || !response.raters.include?(@current_user.id.to_s)
            if response.language == "English"
              @english_responses << response
            else
              @spanish_responses << response
            end
            # @available_responses << response
          end

            end
          end
	end
     end

    end


    # popup QARs per 20 responses
    @english_qars = []
    @spanish_qars = []

    if @current_user.total_rated % 20 == 0

      @qars = Qar.all
      @qars.each do |qar|
        if qar.raters.nil? || !qar.raters.include?(@current_user.id.to_s)
          if qar.language == "English"
            @english_qars << qar
          else
            @spanish_qars << qar
          end
        end
      end

    end

    # data = {:message => @spanish_responses, :status => "false"}
    # return render :json => data, :status => :ok

    # data = {:message => @spanish_responses, :status => "false"}
    #  return render :json => data, :status => :ok

    #  @available_responses = {}
    #  @final_available_responses = {}
     #
    #  if @complete_tests.count.to_i > 0
    #    @complete_tests.each do |complete_test|
     #
    #    end
    #  end


    #  if @responses.count.to_i > 0
    #      @responses.each do |response|
    #          if @available_responses["test"+response.test_record_id.to_s].nil?
    #              @available_responses["test"+response.test_record_id.to_s] = []
    #          end
     #
    #          @available_responses["test"+response.test_record_id.to_s] << response
    #      end
     #
    #      @final_available_responses = @available_responses
     #
    #      if !@available_responses.nil?
    #          @available_responses.each do |key,  val|
    #              if val.count.to_i > 0
    #                  val.each_with_index do |val_d, index|

                         # tmp_skip = 0
 #
                         # tmp_worst = val_d.worse_than
                         # tmp_as_good_as = val_d.as_good_as
                         # tmp_better_than = val_d.better_than


    #                  end
    #              end
    #          end
    #      end
     #
    #  end

    #  data = {:message => @available_responses, :status => "false"}
    #  return render :json => data, :status => :ok

  end

  def rate_response

    if !@current_user.rater? && !@current_user.admin?
      return redirect_to "/home"
    end

    @response = Response.find(params[:id])

    if !@response.raters.nil? && @response.raters.include?(@current_user.id.to_s)

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= simple_form_for(@response) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/responses/index.html.erb
<%=render "/users/header" %>
<div class="container-fluid">
  <div class="row" id="content-outter">
    <%=render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">
        <div class="contact-us">
          <div class="row">
            <% if notice %>
              <p id="notice"><%= notice %></p>
            <% end %>
            <div class="h1-style-user">Response</div>
          </div>
          <div class="row">
            <div class="col-md-4 col-xs-6 flex">
              <%= link_to 'Create Response', new_response_path, method: :get, :class => 'btn btn-user-link flex-item' %>
            </div>
            <div class="col-md-8 col-xs-6 text-right flex-end">
              <div class="btn-group paginate-search" role="group" aria-label="search">
                <!--<input type="text" id="text-title" name="title" class="btn btn-default" placeholder="Search Title...">-->
                <input type="text" id="text-parrotid" name="parrotid" class="btn btn-default" placeholder="Search Parrot ID...">
                <input type="text" id="text-firstname" name="firstname" class="btn btn-default" placeholder="Search Firstname...">
                <!--<input type="text" id="text-testid" name="testid" class="btn btn-default" placeholder="Search Test ID...">-->
                <button type="button" class="btn btn-default btn-search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
              </div>
              <%= will_paginate @responses, renderer: 'PaginateHelper::LinkRenderer' %>
            </div>
          </div>
          <div class="row">
            <table class="tb-admin-tests">
              <thead>
                <tr>
                  <th>Set as BMR</th>
                  <th>Response Titles</th>
                  <th>Language</th>
                  <th>Industry</th>
                  <th class="sortable-level asc">Level</th>
                  <th class="sortable-p-date asc">Test Date</th>
                  <th class="sortable-rating asc">Rating</th>
                  <th class="sortable-parrot-id asc">Parrot ID</th>
                  <!--<th class="sortable-user-id asc">User ID</th>-->
                  <th class="sortable-id asc">First Name</th>
                  <th>Edit</th>
                  <th>Trash</th>
                </tr>
              </thead>

              <tbody>
                <% @responses.each do |response| %>
                  <tr>
                    <td>
                      <label class="switch">
                        <% if response.response_type == 1 %>
                          <input type="checkbox" value="<%= response.id %>" class="btn-on-off" checked="true">
                        <% else %>
                          <input type="checkbox" value="<%= response.id %>" class="btn-on-off">
                        <% end %>
                      <span class="slider"></span>
                      </label>
                   </td>
                    <td><%= response.title %></td>
                    <td><%= response.language %></td>
                    <td><%= response.industry %></td>
                    <td><%=response.level %></td>
                    <td><%= if response.created_at.blank? then "" else response.created_at.strftime('%m/%d/%Y') end  %></td>
                    <td><%= response.score %></td>
                    <td><%= User.find_by_id(response.user_id).parrot_id %></td>
                    <!--<td><%= User.find_by_id(response.user_id).id %></td>-->
                    <td><%= User.find_by_id(response.user_id).f_name %></td>
                    <td><%= link_to edit_response_path(response) do %><i class="fa fa-pencil" aria-hidden="true"></i><% end %></td>
                    <td><%= link_to response, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-trash" aria-hidden="true"></i><% end %></td>
                  </tr>
                  <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<%=render "/users/footer" %>
<script>
$( "li.admin-response" ).addClass( "active" );
$(".sortable-level").click(function(){
    var o = $(this).hasClass('asc') ? 'desc' : 'asc';
    $(".sortable-level").removeClass('asc').removeClass('desc');
    $(this).addClass(o);
    var colIndex = $(this).prevAll().length;
    var tbod = $(this).closest("table").find("tbody");
    var rows = tbod.find("tr");

    rows.sort(function(a,b){
        var A = $(a).find("td").eq(colIndex).text();
        var B = $(b).find("td").eq(colIndex).text();

        if (!isNaN(A)) A = Number(A);
        if (!isNaN(B)) B = Number(B);

        return o == 'asc' ? A > B : B > A;
    });

    $.each(rows, function(index, ele){
        tbod.append(ele);
    });
});
$(".sortable-p-date").click(function(){
    var o = $(this).hasClass('asc') ? 'desc' : 'asc';
    $(".sortable-p-date").removeClass('asc').removeClass('desc');
    $(this).addClass(o);
    var colIndex = $(this).prevAll().length;
    var tbod = $(this).closest("table").find("tbody");
    var rows = tbod.find("tr");

    rows.sort(function(a,b){
        var A = $(a).find("td").eq(colIndex).text();
        var B = $(b).find("td").eq(colIndex).text();

        if (!isNaN(A)) A = Number(A);
        if (!isNaN(B)) B = Number(B);

        return o == 'asc' ? A > B : B > A;
    });

    $.each(rows, function(index, ele){
        tbod.append(ele);
    });
});
$(".sortable-rating").click(function(){
    var o = $(this).hasClass('asc') ? 'desc' : 'asc';
    $(".sortable-rating").removeClass('asc').removeClass('desc');
    $(this).addClass(o);
    var colIndex = $(this).prevAll().length;
    var tbod = $(this).closest("table").find("tbody");
    var rows = tbod.find("tr");

    rows.sort(function(a,b){
        var A = $(a).find("td").eq(colIndex).text();
        var B = $(b).find("td").eq(colIndex).text();

        if (!isNaN(A)) A = Number(A);
        if (!isNaN(B)) B = Number(B);

        return o == 'asc' ? A > B : B > A;
    });

    $.each(rows, function(index, ele){
        tbod.append(ele);
    });
});
$(".sortable-parrot-id").click(function(){
    var o = $(this).hasClass('asc') ? 'desc' : 'asc';
    $(".sortable-parrot-id").removeClass('asc').removeClass('desc');
    $(this).addClass(o);
    var colIndex = $(this).prevAll().length;
    var tbod = $(this).closest("table").find("tbody");
    var rows = tbod.find("tr");

    rows.sort(function(a,b){
        var A = $(a).find("td").eq(colIndex).text();
        var B = $(b).find("td").eq(colIndex).text();

        if (!isNaN(A)) A = Number(A);
        if (!isNaN(B)) B = Number(B);

        return o == 'asc' ? A > B : B > A;
    });

    $.each(rows, function(index, ele){
        tbod.append(ele);
    });
});
$(".sortable-user-id").click(function(){
    var o = $(this).hasClass('asc') ? 'desc' : 'asc';
    $(".sortable-user-id").removeClass('asc').removeClass('desc');
    $(this).addClass(o);
    var colIndex = $(this).prevAll().length;
    var tbod = $(this).closest("table").find("tbody");
    var rows = tbod.find("tr");

    rows.sort(function(a,b){
        var A = $(a).find("td").eq(colIndex).text();
        var B = $(b).find("td").eq(colIndex).text();

        if (!isNaN(A)) A = Number(A);
        if (!isNaN(B)) B = Number(B);

        return o == 'asc' ? A > B : B > A;
    });

    $.each(rows, function(index, ele){
        tbod.append(ele);
    });
});
// AJAX for on-off-button

$('.btn-on-off').click(function() {
  var response_type = 0;
  if ($(this).is(':checked')) {
    response_type = 1;
  }else {
    response_type = 0;
  }
  var response_id = $(this).val();
  console.log('response_type =' + response_type);
  console.log('response_id = ' + response_id);
  $.ajax({
    url: '/change_response_type',
    type: 'post',
    data: {
      response_type : response_type,
      response_id : response_id
    },
    // success: function() {console.log(data);},
    // error: function() {console.log('error');}
  });
  // console.log(data);
});

$(function() {
  $('.btn-search').click(function(){
    //if($('#text-title').val() !== ''){
      //location.href = '/responses?title=' + $('#text-title').val();
    //}
    if($('#text-parrotid').val() !== ''){
      location.href = '/responses?parrotid=' + $('#text-parrotid').val();
    }
    if($('#text-firstname').val() !== ''){
      location.href = '/responses?firstname=' + $('#text-firstname').val();
    }
    //if($('#text-testid').val() !== ''){
      //location.href = '/responses?testid=' + $('#text-testid').val();
    //}
  });

  function initSearchText(){
    var url = new URL(location.href);
    var title = url.searchParams.get("title");
    var parrotid = url.searchParams.get("parrotid");
    var firstname = url.searchParams.get("firstname");
    var testid = url.searchParams.get("testid");

    //if(title !== null && title !== ''){
      //$('#text-title').val(title);
    //}
    if(parrotid !== null && parrotid !== ''){
      $('#text-parrotid').val(parrotid);
    }
    if(firstname !== null && firstname !== ''){
      $('#text-firstname').val(firstname);
    }
    //if(testid !== null && testid !== ''){
      //$('#text-testid').val(testid);
    //}
  }

  initSearchText();
});
</script>

app/views/responses/rater_available.html.erb
<%=render "/users/header" %>
<div class="container-fluid">
  <div class="row" id="content-outter">
    <%=render "/users/siderbar" %>
    <div class="col-md-10">
      <div class="content container-fluid">
        <div class="rate-available">
          <div class="row">
            <% if notice %>
              <p id="notice"><%= notice %></p>
            <% end %>
            <div class="h1-style-user">Response</div>
          </div>
          <div class="row">
            <div class="h2-style-user">Photos Waiting for Verification</div>
          </div>
          <div class="row">
            <table class="tb-response">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>Language</th>
                  <th>Industry</th>
                  <th>Test Date</th>
                  <th>Verify Photo</th>
                </tr>
              </thead>
              <tbody>
                <% if !@wait_for_verify_tests.nil? %>
                  <% @wait_for_verify_tests.each do |wvt| %>

                    <tr>
                      <td><%= wvt.test_name %></td>
                      <td><%= wvt.language %></td>
                      <td><%= wvt.industry %></td>
                      <td><%= if wvt.created_at.blank? then " " else wvt.created_at.strftime('%m/%d/%Y') end  %></td>
                      <td><%= link_to 'Verify Now', photo_verification_path(wvt), :class=>"rate-now" %></td>
                    </tr>

                  <% end %>
              <% end %>
              </tbody> 
            </table>
          </div>
          <div class="row">
            <div class="h2-style-user">English</div>
          </div>
          <div class="row">
            <table class="tb-response">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>Industry</th>
                  <th>Test Date</th>
                  <th>Rate Response</th>
                </tr>
              </thead>
              <tbody>
              <% @english_responses.first(1).each do |er| %>

                    <tr>
                      <td><%= er.title %></td>
                      <td><%= er.industry %></td>
                      <td><%= if er.created_at.blank? then "" else er.created_at.strftime('%m/%d/%Y') end %></td>
                      <td><%= link_to 'Rate Now', rate_response_path(er), :class=>"rate-now" %></td>
                    </tr>

              <% end %>
              <% @english_qars.first(1).each do |eq| %>

                <tr>
                  <td><%= eq.title %></td>
                  <td><%= eq.industry %></td>
                  <td><%= if eq.created_at.blank? then "" else eq.created_at.strftime('%m/%d/%Y') end %></td>
                  <td><%= link_to 'Rate Now', qar_path(eq), :class=>"rate-now" %></td>
                </tr>

              <% end %>
              </tbody>
            </table>
          </div>
          <div class="row">
            <div class="h2-style-user">Spanish</div>
          </div>
          <div class="row">
            <table class="tb-response">
              <thead>
                <tr>
                  <th>Test</th>
                  <th>Industry</th>
                  <th>Test Date</th>
                  <th>Rate Response</th>
                </tr>
              </thead>
              <tbody>
              <% @spanish_responses.first(1).each do |sr| %>
                    <tr>
                      <td><%= sr.title %></td>
                      <td><%= sr.industry %></td>
                      <td><%= if sr.created_at.blank? then "" else sr.created_at.strftime('%m/%d/%Y') end %></td>
                      <td><%= link_to 'Rate Now', rate_response_path(sr), :class=>"rate-now" %></td>
                    </tr>
              <% end %>
              <% @spanish_qars.first(1).each do |sq| %>

                <tr>
                  <td><%= sq.title %></td>
                  <td><%= sq.industry %></td>
                  <td><%= if sq.created_at.blank? then "" else sq.created_at.strftime('%m/%d/%Y') end %></td>
                  <td><%= link_to 'Rate Now', qar_path(sq), :class=>"rate-now" %></td>
                </tr>

              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%=render "/users/footer" %>

<script type="text/javascript">
  $( "li.user-response" ).addClass( "active" );
</script>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>