config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :homes
  resources :contacts, only: [:new, :create]
  resources :users, only: [:index, :new, :create, :update, :show, :destroy]
  resources :messages, only: [:update, :show, :edit, :destroy]
  resources :tests , except: [:update]
  #PDF feature
  resources :invoices, only: [:index, :show]
  resources :invoices, only: [:index, :show] do
    resource :download, only: [:show]
  end

  # resources :carts do
  #   collection do
  #     delete :clean
  #   end
  # end
  # resources :items, controller: 'cart_items'
  resources :payment_records
  resources :payout_records
  resources :test_records
  resources :qars
  resources :prompts
  resources :responses

  delete 'logout'  => 'sessions#destroy'
  get '/resendtokenpage' => 'application#resendtokenpage'
  post '/resendtoken' => 'application#resendtoken'
  get '/resendtokensuccessful' => 'application#resendtokensuccessful'

  get '/activeuser' => 'application#activeuser'

  post '/forget_email' => 'application#forget_email'
  post '/forget_password' => 'application#forget_password'

  get '/resetpassword' => 'application#getresetpassword'
  post '/resetpassword' => 'application#postresetpassword'

  get '/resetpasswordsuccessful' => 'application#resetpasswordsuccessful'


  match '/login' => 'users#login', :via => [:post, :get]
  match '/logout' => 'users#logout', :via => [:post, :get]

  get '/thankyou' => 'homes#thankyou'

  get '/active_link_done' => 'homes#active_link_done'
  get '/active_link_fail' => 'homes#active_link_fail'

  # homes inner pages routes
  # get '/howitworks' => 'homes#howitworks'
  # get '/aboutthetests' => 'homes#aboutthetests'
  # get '/aboutparrot' => 'homes#aboutparrot'
  # get '/parrotforbusiness' => 'homes#parrotforbusiness'
  # get '/howtobecomeaparrotrater' => 'homes#howtobecomeaparrotrater'
  # get '/contactus' => 'homes#contactus'
  # get '/test' => 'homes#testtemplate'
  # get '/faq' => 'homes#faq'
  # get '/privatepolicy' => 'homes#privatepolicy'
  get '/test_introduction/:id(.:format)' => 'homes#test_introduction', :as => 'test_introduction'
  match '/search_tests' => 'homes#search_tests', :via => [:post, :get]
  get '/notfound' => 'application#not_found'



  # cart
  # post '/save_item' => 'tests#save_item'
  post '/add_to_cart' => 'tests#add_to_cart'
  get '/cart_number_reload' => 'homes#cart_number_reload'
  get '/cart' => 'carts#cart'
  post '/delete_item' => 'carts#delete_item'
  post '/clean_cart' => 'carts#clean_cart'
  post '/cart_login' => 'carts#cart_login'

  # payment
  get '/checkout' => 'paypals#new'
  post '/checkout_with_credit_card' => 'paypals#checkout_with_credit_card'
  post '/checkout_with_paypal' => 'paypals#checkout_with_paypal'
  get '/thankyoupurchase' => 'paypals#thankyoupurchase'
  post '/cancel_order' => 'paypals#cancel_order'
  get '/payout_new' => 'paypals#payout_new'
  match '/payout_create' => 'paypals#payout_create', :via => [:post, :get]
  get '/payment_pdf' => 'payment_records#download_payment_pdf'


  # admin home
  get '/dashboard' => 'users#dashboard'
  get '/cashflow' => 'users#cashflow'
  get '/invite' => 'users#invite'
  post '/invite_user' => 'users#invite_user'
  post '/invite_as_rater' => 'users#invite_as_rater'
  get '/cheating/:id(.:format)' => 'users#cheating', :as => 'cheating'
  post '/change_user_status' => 'users#change_user_status'

  # cms
  get '/cms' => 'users#cms'
  get '/cms/:id/edit(.:format)' => 'users#page_edit', :as => 'page_edit'
  post '/tinymce_assets' => 'users#upload_image'
  put '/cms/content_update/:id(.:format)' => 'users#content_update', :as => 'content_update'

  # user home
  get '/home' => 'users#home'
  get '/account' => 'users#edit', :as => 'edit_user'
  get '/payment' => 'payment_records#index'
  get '/test_brief/:id(.:format)' => 'tests#test_brief', :as => 'test_brief'
  post '/test_checkout' => 'tests#test_checkout'
  # get '/prompts' => 'users#prompts'
  # post '/change_password' => 'users#change_password'
  get '/certificate_pdf' => 'users#download_certificate_pdf'

  # rater home
  get '/rating_history' => 'users#rating_history'

  # test
  put '/tests/:id(.:format)' => 'tests#update', :as => 'test_update'
  get '/sendscores' => 'test_records#sendscores'
  get '/score_histiry' => 'test_records#score_histiry'
  post '/send_response' => 'tests#send_response'
  post '/close_test' => 'tests#close_test'
  get '/finished_test' => 'tests#finished_test'
  # get '/test_begin_camera' => 'test_records#test_begin_camera'
  post '/post_test_begin_photo' => 'test_records#post_test_begin_photo'
  # get '/test_end_camera' => 'test_records#test_end_camera'
  post '/post_test_end_photo' => 'test_records#post_test_end_photo'
  post '/window_lose_focus' => 'tests#window_lose_focus'
  post '/take_practice_test/:id(.:format)' => 'tests#take_practice_test', :as => 'take_practice_test'

  # response
  post '/change_response_type' => 'responses#change_response_type'
  post '/audio_record_create' => 'responses#audio_record_create'
  get '/rater_available' => 'responses#rater_available'
  get '/photo_verification/:id(.:format)' => 'test_records#photo_verification', :as => 'photo_verification'
  post '/post_photo_verification' => 'test_records#post_photo_verification'
  get '/rate_response/:id(.:format)' => 'responses#rate_response', :as => 'rate_response'
  match '/give_a_rate' => 'responses#give_a_rate', :via => [:post, :get]
  post '/test_answer' => 'responses#test_answer'
  # get '/recorder' => 'responses#recorder'
  post '/qar_submit' => 'qars#qar_submit'

  # Contact us
  get '/contact_us' => 'messages#index', :as => 'messages'
  get '/new_message' => 'messages#new', :as => 'new_message'
  post '/contact_us' => 'messages#create'
  post '/message_delete' => 'messages#delete'
  post '/message_reply' => 'messages#reply'
  get '/inbox_reload' => 'messages#inbox_reload'
  get '/sendbox_reload' => 'messages#sendbox_reload'


  get '/:slug' => 'homes#find_page'
  # get '*slug' => 'application#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  # has_many :cart_items, dependent: :destroy
  # has_many :items, through: :cart_items, source: :test

  # def add_test_to_cart(test)
  #   ci = cart_items.build
  #   ci.test_id = test
  #   ci.save
    # data = {:message => ci, :status => "false"}
    # return render :json => data, :status => :ok
  # end

  # def total_price
  #   sum = 0
  #   items.each do |item|
  #     sum = sum + item.price.to_d
  #   end
  #
  #   sum.to_s
  # end

  # def clean!
  #   cart_items.destroy_all
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :anti_authuser
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cart
    @pages = Page.all

    @howitworks = @pages[1]
    @aboutthetests = @pages[2]
    @aboutparrot = @pages[3]
    @parrotforbusiness = @pages[4]
    @howtobecomeaparrotrater = @pages[5]
    @footer = @pages[8]

    if session[:cart_expires_at].nil?
      session[:tests] = []
    elsif session[:cart_expires_at].to_time < Time.current
      session[:tests] = []
    end

    @cart_items = session[:tests]

    if !@cart_items.nil?
      # caculate price
      @sum = 0
      @cart_items.each do |cart_item|
        @test = Test.find_by_id(cart_item)

        @sum = @sum + @test.price.to_d
      end

      @sum = @sum.to_s
      session[:total_price] = @sum
    else
      @sum = "0.00"
    end

  end

  def clean_cart
    session[:tests] = nil
    # data = {:message => session[:tests], :status => "true"}
    # return render :json => data, :status => :ok
    # data = {:message => $tests, :status => "true"}
    respond_to do |format|
      format.html { redirect_to cart_path, alert: 'Cart has been cleared.' }
      format.json { render :json => data, :status => :ok }
    end
  end

  def delete_item
    @delete_item = params[:item].to_i
    # @test = Test.find_by_id(@delete_item)

    session[:tests].delete_at(@delete_item)
    $tests.delete_at(@delete_item)

    # data = {:message => session[:tests][@delete_item], :message2 => session[:tests], :status => "false"}
    # return render :json => data, :status => :ok

    data = {:message => session[:tests], :status => "true"}

    respond_to do |format|
      format.html { redirect_to cart_path, alert: ' the item has been deleted.' }
      format.json { render :json => data, :status => :ok }
    end
  end

  def cart_login
    @email =  params[:email]
    @password = params[:password]

    # data = {:message => @price, :status => "false"}
    # return render :json => data, :status => :ok

    @current_user = User.find_by_email(@email)

    if @current_user == nil
      data = {:message => "This user was not found in the system.", :status => "false"}
      return render :json => data, :status => :ok
    end

    @current_user_password = @current_user["password"]
    @id = @current_user["id"]

    @encrypted_password = BCrypt::Password.new(@current_user_password)
    @auth = (@encrypted_password == @password)

    if @auth != true
      data = {:message => "The password entered does not match the password for this account. Please try again.", :status => "false"}
      return render :json => data, :status => :ok
    end


    @current_user_confirm_id = @current_user["id"]
    @current_user_status = @current_user["status"]

    # if @current_user_status.to_s != "1"
      # data = {:message => "Your Account is Disable, Please contact your admin to enable it.", :status => "false"}
      # return render :json => data, :status => :ok
    # end

    session[:user_id] = @current_user_confirm_id
    session[:status] = @current_user_status
    session[:expires_at] = Time.current + 1.hours


    @db.query("UPDATE users SET updated_at=now() WHERE email='"+@email.to_s+"'")

    # return redirect_to checkout_path

    # data = {:message => "Logged In", :user_id => @current_user_confirm_id, :status => "true"}
    # return render :json => data, :status => :ok

    respond_to do |format|
      format.html { redirect_to checkout_path }
      format.json { render json: data, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  # def cart_total_price(cart)
  #   cart.total_price
  # end
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/cart.html.erb
<%=render "homes/header" %>
<div class="check-out">
  <div class="container section">
    <div class="col-md-12">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="h1-style">Cart</div>

      <div class="row container-fluid">
        <table class="tb-cart">
          <thead>
            <th>Purchase(s)</th>
            <th>Amount (US$)</th>
            <th></th>
          </thead>
          <tbody>
            <% if !@cart_items.nil? %>
              <% @cart_items.each_with_index do |cart_item, index| %>
              <% test = Test.find_by_id(cart_item) %>
                <tr>
                  <td><%= test.title %></td>
                  <td><%= test.price %></td>
                  <td>
                    <button class="btn item_del" value="<%= index %>" data-toggle="modal" data-target="#loading-modal">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                  </td>
                </tr>
              <% end %>
            <% else %>
            <% end %>
          </tbody>
        </table>
        <div class="cart-bottom">
          <div class="col-md-6"></div>
          <div class="col-md-6 cart-bottom-inner">
            <div class="table-total">
        <table class="tb-total">
          <tbody>
            <tr>
              <td>Subtotal:</td>
              <td><%= @sum %> US$</td>
            </tr>
            <tr>
              <td>Grand Total:</td>
              <td><%= @sum %> US$</td>
            </tr>
          </tbody>
        </table>
</div>
          <div class="btn-cart">
            <div class="btn-cart-item here"><button id="clear_cart" class="btn-clear" data-toggle="modal" data-target="#loading-modal">Clear Cart</button></div>
            <div class="btn-cart-item btn btn-color"><%= link_to 'View More Tests', '/aboutthetests' %></div>
            <div class="btn-cart-item btn btn-color"><a href="#modal-cart-login" data-toggle="modal" class="modal-activate" id="cart-login-btn">Check Out</a></div>
          </div>
          </div>
          </div>
      </div>

      <!-- loading modal -->
      <div id="loading-modal" class="modal fade">
        <div class="modal-out">
          <div class="modal-dialog">
            <div class="circle spinner2"></div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<%=render "homes/footer" %>

<!-- login-modal -->
<div id="modal-cart-login" class="modal fade">
  <div class="modal-out">
    <div class="modal-dialog">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="modal-header">
          <h4 class="modal-title"><%= image_tag ( "homepage/logo-86x85.png") %></h4>
          <div class="h1-top-style">Login Your Parrot Account</div>
        </div>
        <div class="modal-body">
          <form id="cart_login_form">
            <div class="form-group">
              <input type="email" class="form-control cart_login" id="cartEmail" name="login_cart_email" aria-describedby="emailHelp" placeholder="Email" autofocus>
            </div>
            <div class="form-group">
              <input type="password" class="form-control cart_login" id="cartPassword" name="login_cart_password" placeholder="Password">
            </div>
          </form>

          <span id="cart_login_error_msg" style="color:red;"></span>
          <br />

          <div class="forgot">
            <a href="#modal-forgot-email" data-toggle="modal" class="modal-activate"  id="forgot-email-btn" data-dismiss="modal">Forgot Email?</a>
            <a href="#modal-forgot-pass" data-toggle="modal" class="modal-activate"  id="forgot-pass-btn" data-dismiss="modal">Forgot Password?</a>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-color" id="cart_login_submit">Welcome Back!</button>
          <span class="new-user forgot">  <%=
              link_to new_user_path do
              %>
            New User?
            <% end %></span>
        </div>
      </div>
    </div>
  </div>
</div>


<script>

// clear cart

$("#clear_cart").click(function(){
  $.post("/clean_cart", {
  });
});

// delete item

$(".item_del").click(function(){
  var item = $(this).val();

  $.post("/delete_item", {
    item: item
  }, function (data, status) {
    if(data.status == "false"){
      // console.log("Data: " + data.status);
      // console.log("Data: " + data.message);
    }else{
      // console.log("Data: " + data.status);
      // console.log("Data: " + data.message);
    }
  });
});

// prevent empty purchase
$("#cart-login-btn").click(function(e){
  if (<%= @sum %> == "0.00") {
    e.preventDefault();
    return false;
  }
});

// cart login
$(".cart_login").keypress(function(e){
    if(e.which === 13){
        $("#cart_login_submit").trigger('click');
        return false;  // Prevent the default button behaviour

    }
});

$("#cart_login_submit").click(function () {

  $( "#cart_login_error_msg" ).empty();

  var email = $('#cartEmail').val();
  var password = $('#cartPassword').val();

    if(email == ""){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>Please Type an Email</p>" );

        return;
    }

    if(password == ""){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>Please Type a Password</p>" );

        return;
    }



    $.post("/cart_login", {
      email: email,
      password: password,
    }, function (data, status) {
      if(data.status == "false"){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>"+data.message+"</p>" );
        return;
      }else{
        // console.log("Data: " + data.status);
        // console.log("Data: " + data.message);
        // window.location.href = "/checkout";
      }
    });
});
</script>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<%=render "homes/header" %>
<div class="check-out">
  <div class="container section">
    <div class="col-md-12">
      <% if notice %>
        <p class="alert alert-success" id="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="h1-style">Cart</div>

      <div class="row container-fluid">
        <table class="tb-cart">
          <thead>
            <th>Purchase(s)</th>
            <th>Amount (US$)</th>
            <th></th>
          </thead>
          <tbody>
            <% items = [] %>
            <% current_cart.items.each do |test| %>
            <% items << test.id %>
              <tr>
                <td><%= link_to(test.title, test_path(test)) %></td>
                <td><%= test.price %></td>
                <td>
                  <%= link_to item_path(test), method: :delete do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="cart-bottom">
          <div class="col-md-6"></div>
          <div class="col-md-6 cart-bottom-inner">
        <table class="tb-total">
          <tbody>
            <tr>
              <td>Subtotal:</td>
              <td><%= cart_total_price(current_cart) %> US$</td>
            </tr>
            <tr>
              <td>Grand Total:</td>
              <td><%= cart_total_price(current_cart) %> US$</td>
            </tr>

          </tbody>
        </table>

          <div class="btn-cart">
            <div class="btn-cart-item here"><%= link_to "Clear Cart", clean_carts_path, method: :delete %></div>
            <div class="btn-cart-item btn btn-color"><%= link_to 'View More Tests', aboutthetests_path %></div>
            <div class="btn-cart-item btn btn-color modal-btn"><a href="#modal-cart-login" data-toggle="modal" class="modal-activate" id="cart-login-btn">Check Out</a></div>
          </div>
          </div>
          </div>


      </div>

    </div>

  </div>
</div>
<%=render "homes/footer" %>

<!-- login-modal -->
<div id="modal-cart-login" class="modal fade">
  <div class="modal-out">
    <div class="modal-dialog">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="modal-header">
          <h4 class="modal-title"><%= image_tag ( "homepage/logo-86x85.png") %></h4>
          <div class="h1-top-style">Login Your Parrot Account</div>
        </div>
        <div class="modal-body">
          <form id="login">
            <div class="form-group">
              <input type="email" class="form-control cart_login" id="cartEmail" name="login_cart_email" aria-describedby="emailHelp" placeholder="Email" autofocus>
            </div>
            <div class="form-group">
              <input type="password" class="form-control cart_login" id="cartPassword" name="login_cart_password" placeholder="Password">
            </div>
          </form>

          <span id="cart_login_error_msg" style="color:red;"></span>
          <br />

          <div class="forgot">
            <a href="#modal-forgot-email" data-toggle="modal" class="modal-activate"  id="forgot-email-btn" data-dismiss="modal">Forgot Email?</a>
            <a href="#modal-forgot-pass" data-toggle="modal" class="modal-activate"  id="forgot-pass-btn" data-dismiss="modal">Forgot Password?</a>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-color" id="cart_login_submit">Welcome Back!</button>
          <span class="new-user forgot">  <%=
              link_to new_user_path do
              %>
            New User?
            <% end %></span>
        </div>
      </div>
    </div>
  </div>
</div>


<script>


var price = <%= cart_total_price(current_cart) %>;
var cart_items = JSON.stringify(<%= items %>.map(String));

// cart login
$(".cart_login").keypress(function(e){
    if(e.which === 13){
        $("#cart_login_submit").trigger('click');
        return false;  // Prevent the default button behaviour

    }
});

$("#cart_login_submit").click(function () {

  $( "#cart_login_error_msg" ).empty();

  var email = $('#cartEmail').val();
  var password = $('#cartPassword').val();

    if(email == ""){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>Please Type an Email</p>" );

        return;
    }

    if(password == ""){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>Please Type a Password</p>" );

        return;
    }


    $.post("/cart_login", {
      email: email,
      password: password,
      price: price,
      cart_items: cart_items
    }, function (data, status) {
      if(data.status == "false"){
        $( "#cart_login_error_msg" ).append( "<p style='color:red;'>"+data.message+"</p>" );
        return;
      }else{
        console.log("Data: " + data.status);
        console.log("Data: " + data.message);
      }
    });
});
</script>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>